language: javascript
deploy:
  provider: firebase
  token:
    secure: "dd2f+xC+zbb3SZ8gEtWs4/F29X4OpwxDpHxyvrX1ZO73FIRaGMzjgnNHoCpuZRrUe5f6\
swaSU3Oh94siP2WtOLMw05Z4KVbAHCUPZtmz7mmZfKI1+Agr9ONXt2O5gpOPZYMTyqlyz5dU3VlGEilZ\
0SkifBVe2zZGXpeTEz6YXKBSpK5f/LZd2zD3XsWY1d0q2OUOu+2m/QWG3b1CvwJ+lfPy0YSJazRgtojF\
cFw+NA5ehb9eDjW2dVfWmLlPVA7fLGdbBTP6XtGOBzFfDJx/v4t5ee/r4eDRYCbDYzRcIXXzfkt8Tnxk\
N5VgkcfvwoFFeofv9ph9Ok+EZOlXghmhgVHoFpLuugKQjz5Xn9xqkCLuB6UnmXS7ipsRCwanvLwkL81z\
USrHzhadzkv8B2u+HuiNOvAqzh2ph3vha+VOL0zpccwBL9X+hcBHt4jz6ahT0jzIeYJaWFaKqfuu/GTR\
EqjrsuircBVXnipVtvqriEJZuPdX4ZjJ8BCvTjTyaf198a6gxQ+uLR6P+9MN4tt6J9W9aNW9JVk1uKCn\
953LAEKwakvV1BHd4+1HtRQ3UO1BmwKg0QFkJDAGjTTJNRdMXp5D9fE94JT9CxXHXo6T54tepktOEqGH\
79eP8Xm5z7v3dhZOpdem8Dl+r5y9RufSp7Fa5TwvOTRVRRts8sEC26Q="
  project: "cryptopurse-staging"
  
